### ISSUE TITLE
failed to install the package 

### ISSUE THREAD

**Issue by yangyijane** [timmens/causal-forest#20]
hi when I tried to install the package in the coda, here is the issue I face: the Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source. Could you help to sort it out?

**Comment by timmens** [comment]
Hey @yangyijane, thanks for reaching out!

Could you give me some more information? Did you use an environment file, or how did you create the environment?

Preferably you provide a minimal working example where the installation fails. In that case I can help you better.

Best, Tim
